In [15]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score

In [16]:
iris = load_iris()
type(iris)

sklearn.datasets.base.Bunch

In [17]:
print(iris.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [18]:
X = iris.data
y = iris.target
X.reshape(1,-1)

array([[ 5.1,  3.5,  1.4,  0.2,  4.9,  3. ,  1.4,  0.2,  4.7,  3.2,  1.3,
         0.2,  4.6,  3.1,  1.5,  0.2,  5. ,  3.6,  1.4,  0.2,  5.4,  3.9,
         1.7,  0.4,  4.6,  3.4,  1.4,  0.3,  5. ,  3.4,  1.5,  0.2,  4.4,
         2.9,  1.4,  0.2,  4.9,  3.1,  1.5,  0.1,  5.4,  3.7,  1.5,  0.2,
         4.8,  3.4,  1.6,  0.2,  4.8,  3. ,  1.4,  0.1,  4.3,  3. ,  1.1,
         0.1,  5.8,  4. ,  1.2,  0.2,  5.7,  4.4,  1.5,  0.4,  5.4,  3.9,
         1.3,  0.4,  5.1,  3.5,  1.4,  0.3,  5.7,  3.8,  1.7,  0.3,  5.1,
         3.8,  1.5,  0.3,  5.4,  3.4,  1.7,  0.2,  5.1,  3.7,  1.5,  0.4,
         4.6,  3.6,  1. ,  0.2,  5.1,  3.3,  1.7,  0.5,  4.8,  3.4,  1.9,
         0.2,  5. ,  3. ,  1.6,  0.2,  5. ,  3.4,  1.6,  0.4,  5.2,  3.5,
         1.5,  0.2,  5.2,  3.4,  1.4,  0.2,  4.7,  3.2,  1.6,  0.2,  4.8,
         3.1,  1.6,  0.2,  5.4,  3.4,  1.5,  0.4,  5.2,  4.1,  1.5,  0.1,
         5.5,  4.2,  1.4,  0.2,  4.9,  3.1,  1.5,  0.1,  5. ,  3.2,  1.2,
         0.2,  5.5,  3.5,  1.3,  0.2, 

In [19]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [20]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [21]:
knn =  KNeighborsClassifier()

In [22]:
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')


In [23]:
X_train,X_test,y_train,y_test = train_test_split(X,y)
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [24]:
pred = knn.predict(X_test)


In [25]:
print("Accuracy: ",accuracy_score(pred,y_test))

Accuracy:  0.947368421053
